Remove erroneous `__slots__` from PollResult
Having an `attrs` class with `weakref_slot=False` at the same time as a
predefined `__slots__` will cause `attrs` to throw a fit:
    TypeError: 'property' object is not iterable